### PR TITLE
Correct auto-link lexing to stop at `<`.

### PR DESCRIPTION
**Pull request by piotrtomiak**
This fixes issue https://youtrack.jetbrains.com/issue/WEB-62513. I've checked with GitHub directly and `<` are indeed a stop for auto-link generation. Once merged, please release 0.5.1, so that I can include it in IJ build.

### CODE REVIEW

**Comment by hurricup** [comment]
This will have merge conflict with https://github.com/JetBrains/markdown/pull/127

**Comment by hurricup** [comment]
We could probably use JFlex 1.9.2 and adjust type a bit

**Comment by piotrtomiak** [comment]
@hurricup It would be great to add this changes to the JFlex-to-Kotlin plugin on code conversion, so that there is as little manual changes as possible. I don't think there should be any hand-made changes done to the generated lexer code. I can recreate the lexer code with JFlex 1.9.2 if that helps.

**Comment by hurricup** [comment]
@piotrtomiak how does this work? You just generate java and convert code by IDE?

**Comment by FirstTimeInForever** [comment]
@piotrtomiak We are hoping to see the bitset changes in the JFlex at some point.

**Comment by FirstTimeInForever** [comment]
@piotrtomiak @hurricup I've been working on an automated lexer generation + conversion to multiplatform during gradle build, however, it is not fully ready yet. Until then, we will unfortunately have to do all the stuff manually by hand.

**Comment by hurricup** [comment]
@FirstTimeInForever it is in 1.9.2

**Comment by FirstTimeInForever** [comment]
OK, let's merge the bitset changes first, then auto links with regenerated lexer.

**Comment by piotrtomiak** [comment]
> @piotrtomiak how does this work? You just generate java and convert code by IDE?

Yes, the process is described in the readme file :)

**Comment by piotrtomiak** [comment]
@hurricup - will you update grammar-kit plugin to use 1.9.2 ?

**Comment by hurricup** [comment]
Or, you can replace artifact downloaded by the plugin (1.9.1) with the proper one (1.9.2) to regen manually.

**Comment by piotrtomiak** [comment]
@FirstTimeInForever - thanks for merging the change! When do you plan to release the new version of the library? The regression is present in 2023.2 and it would be great to have it fixed in 2023.2.3

**Comment by FirstTimeInForever** [comment]
@piotrtomiak I'm releasing a snapshot version rn. I'll need to test the snapshot and when release the stable version. Hopefully it won't take longer than a day.

**Pull request merged**
