### PR TITLE
Enable iOS build target

### LINKED ISSUE #66: Enable iOS build target
The iOS target is currently disabled due to the fact that enabling it would cause tests to fail on CI. This is because there are a number of tests that rely on files in the test resources directory, but iOS tests run on the simulator, and don't have access to the local file system.

Here are a few of the ways we could do this:

1. Just enable the target and accept failing CI builds. Not ideal.
2. Move the file-based tests to `jvmTest` to only run them only on JVM. A couple of tests like the performance tests are already JVM-only.
3. Create an intermediate source set like `nonIosTest` or `desktopTest` and move the file-based tests there. 
4. Remove all file-based tests currently in `commonTest`. Not ideal, since some of them test functionality not covered by the spec tests.
5. Find a way to copy the test resources into the simulator before running the tests.

It would be great to publish the iOS target in the next release, so I'd love to hear your thoughts on if there's any approach you prefer.

### PR DESCRIPTION
**Pull request by ajalt**
iOS was disabled due to the fact that the test suite accessed files on the local file system which accessible on the simulator. This commit moves all such tests to a new source set: `fileBasedTest`. All test source set except `ios` depend on this new source set, so running `gradle test` on any platform will run all tests that run on that platform.

The resources for the performance test were moved into `jvmTest` instead of `fileBasedTest`, since the performance test is jvm-only.

Fixes #66

### CODE REVIEW

**Comment by valich** [comment]
I've merged this one manually due to simple conflicts I had to resolve in IDE.

Now the remaining question (an old one) is how to publish this thing to maven with all platform-dependent publications together. I remember you were saying that you have a working example of such thing on github actions, could you send me a link once more? I will try to set similar thing on TC

**Comment by ajalt** [comment]
Great! Here's [a blog post talking about using multiple GitHub Actions runners to publish artifacts for the various KMP targets](https://www.alecstrong.com/posts/github-actions-mpp/).

Here's the [workflow of one of my projects that publishes to the various targets](https://github.com/ajalt/clikt/blob/master/.github/workflows/publish.yml). I use the windows runner to publish the mingw target, and the mac runner to publish everything else. Once all targets have been published to the Sonatype staging repository, I go in to their UI and release all the artifacts manually.

For versioning the artifacts, I fetch the git tags and [use them in a gradle script](https://github.com/ajalt/clikt/blob/16be0429f4a74271ccafaae36d56ef86eaa19027/build.gradle.kts#L20-L34) to determine the current version, and whether it's a snapshot or not. Many projects just manually write the snapshot version in `gradle.properties`, so you could do something like that instead if you want.

**Comment by valich** [comment]
Oh. I somehow thought that one has to collect all the artifacts on a single machine and then publish everything for all OSes from it. If we can do two publications (from macOS and Windows), that's pretty doable, I will try it now.

We store versions in `gradle.properties` and I'm fine with bumping version manually for now :)

**Comment by valich** [comment]
I've set up agents on TC and have released 0.2.3 to maven-central (they should appear tomorrow, I believe)

This is probably very obvious, but I've just realized, this whole thing actually works because
1. Different OS targets are actually different artifacts with different ids
2. Even if some OS can't produce artifacts for all targets, it still produces the correct `.module` file referencing nonexistnent (yet) artifacts

**Pull request closed without merging**
